[package]
name = "FerrisPanel"
version = "0.1.0"
authors = ["DankDumpster <staalkoper@gmail.com>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[dependencies]

[dependencies.actix-web]
version = "3.0"