[package]
name = "ferris_panel"
version = "0.1.0"
authors = ["DankDumpster <dev@mtbk.me>"]
edition = "2018"

[workspace]
members = ["crates/*", "cli"]

[dependencies]
bcrypt = "0.9.0"

[dependencies.actix-web]
version = "3.0"