services:
  database:
    image: postgres
#    volumes:
#      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  ferrispanel:
    build: .
    ports:
      - "3000:3000"


#volumes:
#  db-data:
#    driver: local