name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd client
      - name: Run ESLint
        run: yarn run --cwd client eslint . --ext .js,.jsx,.ts,.tsx